version: '2'
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}
services:
  zookeeper:
    image: nexus3.onap.org:10001/onap/dmaap/zookeeper:1.0.0
    ports:
      - "2181:2181"
    volumes:
      - ./data-zookeeper:/var/lib/zookeeper/data
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  kafka:
    #CADI integrated kafka image
    #image: nexus3.onap.org:10001/onap/dmaap/kafka01101:0.0.2
    image: nexus3.onap.org:10001/onap/dmaap/kafka01101:0.0.1
    ports:
      - "9092:9092"
    environment:
      enableCadi: 'false'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #Properties required for using the CADI integrated Kafka
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT,EXTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: INTERNAL_SASL_PLAINTEXT://kafka:9092
      #KAFKA_LISTENERS: INTERNAL_SASL_PLAINTEXT://0.0.0.0:9092
      #KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SASL_PLAINTEXT
      #KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      #KAFKA_AUTHORIZER_CLASS_NAME: org.onap.dmaap.kafkaAuthorize.KafkaCustomAuthorizer
      #aaf_locate_url: https://aaf-onap-test.osaaf.org:8095
      #Remove the below 4 properties if CADI
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: INTERNAL_PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  dmaap:
    image: ${NEXUS_DOCKER_REPO}/onap/dmaap/dmaap-mr:1.1.9
    ports:
      - "3904:3904"
      - "3905:3905"
    volumes:
      - ./MsgRtrApi.properties:/appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties 
      - ./cadi.properties:/appl/dmaapMR1/etc/cadi.properties 
      - ./keystore.jks:/appl/dmaapMR1/bundleconfig/etc/keystore.jks 
    depends_on:
      - zookeeper
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
