version: '2'
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data-zookeeper:/opt/zookeeper-3.4.9/data
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: {{ ip.docker0 }}
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data-kafka:/kafka
      - ./start-kafka.sh:/start-kafka.sh
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  dmaap:
    image: ${NEXUS_DOCKER_REPO}/onap/dmaap/dmaap-mr:1.1.4
    ports:
      - "3904:3904"
      - "3905:3905"
    volumes:
      - ./MsgRtrApi.properties:/appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties 
      - ./cadi.properties:/appl/dmaapMR1/etc/cadi.properties 
      - ./keystore.jks:/appl/dmaapMR1/bundleconfig/etc/keystore.jks 
    depends_on:
      - zookeeper
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
