version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
   image: wurstmeister/kafka:0.8.1.1-1
   ports:
    - "9092:9092"
   environment:
    HOSTNAME_COMMAND: "hostname -i"
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
   depends_on:
    - zookeeper

  dmaap:
    image: nexus3.onap.org:10001/onap/dmaap/dmaap-mr
    ports:
      - "3904:3904"
      - "3905:3905"
    volumes:
      - /var/tmp/MsgRtrApi.properties:/appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties
    depends_on:
      - zookeeper
      - kafka
